config/routes.rb
Hafiz::Application.routes.draw do
  resources :recitators

  get "surahs" => "surahs#index"
  post "surahs" => "surahs#index"
  get "pages/home"
  root :to => 'surahs#index'

  devise_for :users
  post '/users/:id/ayahs' , to: 'ayah_relationships#create'
  put '/users/:id/ayahs' , to: 'ayah_relationships#update'
  delete '/relationships/:id' , to: 'ayah_relationships#destroy'

  namespace :api do
    namespace :v1 do
      get "get_url_amazon" => "amazon#get_url"
      devise_scope :user do
        post 'sessions' => 'sessions#create', :as => 'login'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
      end
    end
  end
end

app/models/recitator.rb
class Recitator < ActiveRecord::Base
  attr_accessible :name, :value
end

app/controllers/recitators_controller.rb
class RecitatorsController < ApplicationController
  # GET /recitators
  # GET /recitators.json
  def index
    @recitators = Recitator.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recitators }
    end
  end

  # GET /recitators/1
  # GET /recitators/1.json
  def show
    @recitator = Recitator.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recitator }
    end
  end

  # GET /recitators/new
  # GET /recitators/new.json
  def new
    @recitator = Recitator.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recitator }
    end
  end

  # GET /recitators/1/edit
  def edit
    @recitator = Recitator.find(params[:id])
  end

  # POST /recitators
  # POST /recitators.json
  def create
    @recitator = Recitator.new(params[:recitator])

    respond_to do |format|
      if @recitator.save
        format.html { redirect_to @recitator, notice: 'Recitator was successfully created.' }
        format.json { render json: @recitator, status: :created, location: @recitator }
      else
        format.html { render action: "new" }
        format.json { render json: @recitator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recitators/1
  # PUT /recitators/1.json
  def update
    @recitator = Recitator.find(params[:id])

    respond_to do |format|
      if @recitator.update_attributes (params[:recitator])
        format.html { redirect_to @recitator, notice: 'Recitator was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recitator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recitators/1
  # DELETE /recitators/1.json
  def destroy
    @recitator = Recitator.find(params[:id])
    @recitator.destroy

    respond_to do |format|
      format.html { redirect_to recitators_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/recitators_helper.rb
module RecitatorsHelper
end

app/views/recitators/_form.html.erb
<%= form_for(@recitator) do |f| %>
  <% if @recitator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recitator.errors.count, "error") %> prohibited this recitator from being saved:</h2>

      <ul>
      <% @recitator.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recitators/edit.html.erb
<h1>Editing recitator</h1>

<%= render 'form' %>

<%= link_to 'Show', @recitator %> |
<%= link_to 'Back', recitators_path %>

app/views/recitators/index.html.erb
<h1>Listing recitators</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @recitators.each do |recitator| %>
  <tr>
    <td><%= recitator.name %></td>
    <td><%= recitator.value %></td>
    <td><%= link_to 'Show', recitator %></td>
    <td><%= link_to 'Edit', edit_recitator_path(recitator) %></td>
    <td><%= link_to 'Destroy', recitator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<div class="dropdown">
  <a class="dropdown-toggle" data-toggle="dropdown" href="#">Dropdown trigger</a>
  <ul class="dropdown-menu">
    <li><a href=><span class="label label-success">Very Good</span></a></li>
    <li><a href=><span class="label label-warning">Good</span></a></li>
    <li><a href=><span class="label label-important">Bad</span></a></li>
    <li role="presentation" class="divider"></li>
    <li><a href=><span class="label label-info">Repeat the verse</span></a></li>
  </ul>
</div>

<div class="dropdown">
  <a class="dropdown-toggle" data-toggle="dropdown" href="">بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ</a>
  <ul class="dropdown-menu">
    <li>
      <a class="label label-success" href="">Very Good</a>
    </li>
    <li>
      <a class="label label-warning" href="">Good</a>
    </li>
    <li>
      <a class="label label-important" href="">Bad</a>
    </li>
  </ul>
</div>


<%= link_to 'New Recitator', new_recitator_path %>

app/views/recitators/new.html.erb
<h1>New recitator</h1>

<%= render 'form' %>

<%= link_to 'Back', recitators_path %>

app/views/recitators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @recitator.name %>
</p>

<p>
  <b>Value:</b>
  <%= @recitator.value %>
</p>


<%= link_to 'Edit', edit_recitator_path(@recitator) %> |
<%= link_to 'Back', recitators_path %>